// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/kaz-as/zip/models"
)

// CheckChunksOKCode is the HTTP code returned for type CheckChunksOK
const CheckChunksOKCode int = 200

/*
CheckChunksOK list of chunks number

swagger:response checkChunksOK
*/
type CheckChunksOK struct {

	/*
	  In: Body
	*/
	Payload []models.ChunkNumber `json:"body,omitempty"`
}

// NewCheckChunksOK creates CheckChunksOK with default headers values
func NewCheckChunksOK() *CheckChunksOK {

	return &CheckChunksOK{}
}

// WithPayload adds the payload to the check chunks o k response
func (o *CheckChunksOK) WithPayload(payload []models.ChunkNumber) *CheckChunksOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the check chunks o k response
func (o *CheckChunksOK) SetPayload(payload []models.ChunkNumber) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CheckChunksOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]models.ChunkNumber, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// CheckChunksNotFoundCode is the HTTP code returned for type CheckChunksNotFound
const CheckChunksNotFoundCode int = 404

/*
CheckChunksNotFound archive not found

swagger:response checkChunksNotFound
*/
type CheckChunksNotFound struct {
}

// NewCheckChunksNotFound creates CheckChunksNotFound with default headers values
func NewCheckChunksNotFound() *CheckChunksNotFound {

	return &CheckChunksNotFound{}
}

// WriteResponse to the client
func (o *CheckChunksNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

/*
CheckChunksDefault generic error response

swagger:response checkChunksDefault
*/
type CheckChunksDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCheckChunksDefault creates CheckChunksDefault with default headers values
func NewCheckChunksDefault(code int) *CheckChunksDefault {
	if code <= 0 {
		code = 500
	}

	return &CheckChunksDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the check chunks default response
func (o *CheckChunksDefault) WithStatusCode(code int) *CheckChunksDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the check chunks default response
func (o *CheckChunksDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the check chunks default response
func (o *CheckChunksDefault) WithPayload(payload *models.Error) *CheckChunksDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the check chunks default response
func (o *CheckChunksDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CheckChunksDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
