// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CheckChunksHandlerFunc turns a function with the right signature into a check chunks handler
type CheckChunksHandlerFunc func(CheckChunksParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CheckChunksHandlerFunc) Handle(params CheckChunksParams) middleware.Responder {
	return fn(params)
}

// CheckChunksHandler interface for that can handle valid check chunks params
type CheckChunksHandler interface {
	Handle(CheckChunksParams) middleware.Responder
}

// NewCheckChunks creates a new http.Handler for the check chunks operation
func NewCheckChunks(ctx *middleware.Context, handler CheckChunksHandler) *CheckChunks {
	return &CheckChunks{Context: ctx, Handler: handler}
}

/*
	CheckChunks swagger:route GET /files/upload checkChunks

check which chunks are not uploaded yet
*/
type CheckChunks struct {
	Context *middleware.Context
	Handler CheckChunksHandler
}

func (o *CheckChunks) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCheckChunksParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
