// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateArchiveHandlerFunc turns a function with the right signature into a create archive handler
type CreateArchiveHandlerFunc func(CreateArchiveParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateArchiveHandlerFunc) Handle(params CreateArchiveParams) middleware.Responder {
	return fn(params)
}

// CreateArchiveHandler interface for that can handle valid create archive params
type CreateArchiveHandler interface {
	Handle(CreateArchiveParams) middleware.Responder
}

// NewCreateArchive creates a new http.Handler for the create archive operation
func NewCreateArchive(ctx *middleware.Context, handler CreateArchiveHandler) *CreateArchive {
	return &CreateArchive{Context: ctx, Handler: handler}
}

/*
	CreateArchive swagger:route POST /files/zip createArchive

create zip archive from custom files
*/
type CreateArchive struct {
	Context *middleware.Context
	Handler CreateArchiveHandler
}

func (o *CreateArchive) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCreateArchiveParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
