// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetFilesUploadHandlerFunc turns a function with the right signature into a get files upload handler
type GetFilesUploadHandlerFunc func(GetFilesUploadParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetFilesUploadHandlerFunc) Handle(params GetFilesUploadParams) middleware.Responder {
	return fn(params)
}

// GetFilesUploadHandler interface for that can handle valid get files upload params
type GetFilesUploadHandler interface {
	Handle(GetFilesUploadParams) middleware.Responder
}

// NewGetFilesUpload creates a new http.Handler for the get files upload operation
func NewGetFilesUpload(ctx *middleware.Context, handler GetFilesUploadHandler) *GetFilesUpload {
	return &GetFilesUpload{Context: ctx, Handler: handler}
}

/*
	GetFilesUpload swagger:route GET /files/upload getFilesUpload

check which chunks are not uploaded yet
*/
type GetFilesUpload struct {
	Context *middleware.Context
	Handler GetFilesUploadHandler
}

func (o *GetFilesUpload) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetFilesUploadParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
