// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetFilesHandlerFunc turns a function with the right signature into a get files handler
type GetFilesHandlerFunc func(GetFilesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetFilesHandlerFunc) Handle(params GetFilesParams) middleware.Responder {
	return fn(params)
}

// GetFilesHandler interface for that can handle valid get files params
type GetFilesHandler interface {
	Handle(GetFilesParams) middleware.Responder
}

// NewGetFiles creates a new http.Handler for the get files operation
func NewGetFiles(ctx *middleware.Context, handler GetFilesHandler) *GetFiles {
	return &GetFiles{Context: ctx, Handler: handler}
}

/*
	GetFiles swagger:route GET /files getFiles

list of files in a zip archive
*/
type GetFiles struct {
	Context *middleware.Context
	Handler GetFilesHandler
}

func (o *GetFiles) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetFilesParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
