// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// InitUploadArchiveHandlerFunc turns a function with the right signature into a init upload archive handler
type InitUploadArchiveHandlerFunc func(InitUploadArchiveParams) middleware.Responder

// Handle executing the request and returning a response
func (fn InitUploadArchiveHandlerFunc) Handle(params InitUploadArchiveParams) middleware.Responder {
	return fn(params)
}

// InitUploadArchiveHandler interface for that can handle valid init upload archive params
type InitUploadArchiveHandler interface {
	Handle(InitUploadArchiveParams) middleware.Responder
}

// NewInitUploadArchive creates a new http.Handler for the init upload archive operation
func NewInitUploadArchive(ctx *middleware.Context, handler InitUploadArchiveHandler) *InitUploadArchive {
	return &InitUploadArchive{Context: ctx, Handler: handler}
}

/*
	InitUploadArchive swagger:route POST /files initUploadArchive

init uploading new zip archive
*/
type InitUploadArchive struct {
	Context *middleware.Context
	Handler InitUploadArchiveHandler
}

func (o *InitUploadArchive) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewInitUploadArchiveParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
