// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostFilesHandlerFunc turns a function with the right signature into a post files handler
type PostFilesHandlerFunc func(PostFilesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostFilesHandlerFunc) Handle(params PostFilesParams) middleware.Responder {
	return fn(params)
}

// PostFilesHandler interface for that can handle valid post files params
type PostFilesHandler interface {
	Handle(PostFilesParams) middleware.Responder
}

// NewPostFiles creates a new http.Handler for the post files operation
func NewPostFiles(ctx *middleware.Context, handler PostFilesHandler) *PostFiles {
	return &PostFiles{Context: ctx, Handler: handler}
}

/*
	PostFiles swagger:route POST /files postFiles

init uploading new zip archive
*/
type PostFiles struct {
	Context *middleware.Context
	Handler PostFilesHandler
}

func (o *PostFiles) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostFilesParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
