// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/kaz-as/zip/models"
)

// PostFilesOKCode is the HTTP code returned for type PostFilesOK
const PostFilesOKCode int = 200

/*
PostFilesOK new upload initialized

swagger:response postFilesOK
*/
type PostFilesOK struct {

	/*
	  In: Body
	*/
	Payload *models.InitUploadSuccess `json:"body,omitempty"`
}

// NewPostFilesOK creates PostFilesOK with default headers values
func NewPostFilesOK() *PostFilesOK {

	return &PostFilesOK{}
}

// WithPayload adds the payload to the post files o k response
func (o *PostFilesOK) WithPayload(payload *models.InitUploadSuccess) *PostFilesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post files o k response
func (o *PostFilesOK) SetPayload(payload *models.InitUploadSuccess) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostFilesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
PostFilesDefault generic error response

swagger:response postFilesDefault
*/
type PostFilesDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostFilesDefault creates PostFilesDefault with default headers values
func NewPostFilesDefault(code int) *PostFilesDefault {
	if code <= 0 {
		code = 500
	}

	return &PostFilesDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the post files default response
func (o *PostFilesDefault) WithStatusCode(code int) *PostFilesDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the post files default response
func (o *PostFilesDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the post files default response
func (o *PostFilesDefault) WithPayload(payload *models.Error) *PostFilesDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post files default response
func (o *PostFilesDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostFilesDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
