// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostFilesUploadHandlerFunc turns a function with the right signature into a post files upload handler
type PostFilesUploadHandlerFunc func(PostFilesUploadParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostFilesUploadHandlerFunc) Handle(params PostFilesUploadParams) middleware.Responder {
	return fn(params)
}

// PostFilesUploadHandler interface for that can handle valid post files upload params
type PostFilesUploadHandler interface {
	Handle(PostFilesUploadParams) middleware.Responder
}

// NewPostFilesUpload creates a new http.Handler for the post files upload operation
func NewPostFilesUpload(ctx *middleware.Context, handler PostFilesUploadHandler) *PostFilesUpload {
	return &PostFilesUpload{Context: ctx, Handler: handler}
}

/*
	PostFilesUpload swagger:route POST /files/upload postFilesUpload

upload a chunk of the previously initialized file
*/
type PostFilesUpload struct {
	Context *middleware.Context
	Handler PostFilesUploadHandler
}

func (o *PostFilesUpload) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostFilesUploadParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
