// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostFilesZipHandlerFunc turns a function with the right signature into a post files zip handler
type PostFilesZipHandlerFunc func(PostFilesZipParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostFilesZipHandlerFunc) Handle(params PostFilesZipParams) middleware.Responder {
	return fn(params)
}

// PostFilesZipHandler interface for that can handle valid post files zip params
type PostFilesZipHandler interface {
	Handle(PostFilesZipParams) middleware.Responder
}

// NewPostFilesZip creates a new http.Handler for the post files zip operation
func NewPostFilesZip(ctx *middleware.Context, handler PostFilesZipHandler) *PostFilesZip {
	return &PostFilesZip{Context: ctx, Handler: handler}
}

/*
	PostFilesZip swagger:route POST /files/zip postFilesZip

create zip archive from custom files
*/
type PostFilesZip struct {
	Context *middleware.Context
	Handler PostFilesZipHandler
}

func (o *PostFilesZip) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostFilesZipParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
