// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/kaz-as/zip/models"
)

// PostFilesUploadOKCode is the HTTP code returned for type PostFilesUploadOK
const PostFilesUploadOKCode int = 200

/*
PostFilesUploadOK OK uploaded (including already uploaded)

swagger:response postFilesUploadOK
*/
type PostFilesUploadOK struct {
}

// NewPostFilesUploadOK creates PostFilesUploadOK with default headers values
func NewPostFilesUploadOK() *PostFilesUploadOK {

	return &PostFilesUploadOK{}
}

// WriteResponse to the client
func (o *PostFilesUploadOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*
PostFilesUploadDefault generic error response

swagger:response postFilesUploadDefault
*/
type PostFilesUploadDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostFilesUploadDefault creates PostFilesUploadDefault with default headers values
func NewPostFilesUploadDefault(code int) *PostFilesUploadDefault {
	if code <= 0 {
		code = 500
	}

	return &PostFilesUploadDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the post files upload default response
func (o *PostFilesUploadDefault) WithStatusCode(code int) *PostFilesUploadDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the post files upload default response
func (o *PostFilesUploadDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the post files upload default response
func (o *PostFilesUploadDefault) WithPayload(payload *models.Error) *PostFilesUploadDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post files upload default response
func (o *PostFilesUploadDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostFilesUploadDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
