// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/kaz-as/zip/models"
)

// NewUploadChunkParams creates a new UploadChunkParams object
//
// There are no default values defined in the spec.
func NewUploadChunkParams() UploadChunkParams {

	return UploadChunkParams{}
}

// UploadChunkParams contains all the bound params for the upload chunk operation
// typically these are obtained from a http.Request
//
// swagger:parameters uploadChunk
type UploadChunkParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*chunk's number or count
	  Required: true
	  In: query
	*/
	QueryChunk int32
	/*
	  Required: true
	  In: body
	*/
	Chunk models.ChunkUploadingParam
	/*archive uid
	  Required: true
	  In: query
	*/
	ID int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewUploadChunkParams() beforehand.
func (o *UploadChunkParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qChunk, qhkChunk, _ := qs.GetOK("chunk")
	if err := o.bindQueryChunk(qChunk, qhkChunk, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		o.Chunk = r.Body
	} else {
		res = append(res, errors.Required("chunk", "body", ""))
	}

	qID, qhkID, _ := qs.GetOK("id")
	if err := o.bindID(qID, qhkID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindQueryChunk binds and validates parameter QueryChunk from query.
func (o *UploadChunkParams) bindQueryChunk(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("chunk", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false

	if err := validate.RequiredString("chunk", "query", raw); err != nil {
		return err
	}

	value, err := swag.ConvertInt32(raw)
	if err != nil {
		return errors.InvalidType("chunk", "query", "int32", raw)
	}
	o.QueryChunk = value

	return nil
}

// bindID binds and validates parameter ID from query.
func (o *UploadChunkParams) bindID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("id", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false

	if err := validate.RequiredString("id", "query", raw); err != nil {
		return err
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("id", "query", "int64", raw)
	}
	o.ID = value

	return nil
}
