// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/kaz-as/zip/models"
)

// UploadChunkOKCode is the HTTP code returned for type UploadChunkOK
const UploadChunkOKCode int = 200

/*
UploadChunkOK OK uploaded (including already uploaded)

swagger:response uploadChunkOK
*/
type UploadChunkOK struct {
}

// NewUploadChunkOK creates UploadChunkOK with default headers values
func NewUploadChunkOK() *UploadChunkOK {

	return &UploadChunkOK{}
}

// WriteResponse to the client
func (o *UploadChunkOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*
UploadChunkDefault generic error response

swagger:response uploadChunkDefault
*/
type UploadChunkDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUploadChunkDefault creates UploadChunkDefault with default headers values
func NewUploadChunkDefault(code int) *UploadChunkDefault {
	if code <= 0 {
		code = 500
	}

	return &UploadChunkDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the upload chunk default response
func (o *UploadChunkDefault) WithStatusCode(code int) *UploadChunkDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the upload chunk default response
func (o *UploadChunkDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the upload chunk default response
func (o *UploadChunkDefault) WithPayload(payload *models.Error) *UploadChunkDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the upload chunk default response
func (o *UploadChunkDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UploadChunkDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
