// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// UploadChunkHandlerFunc turns a function with the right signature into a upload chunk handler
type UploadChunkHandlerFunc func(UploadChunkParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UploadChunkHandlerFunc) Handle(params UploadChunkParams) middleware.Responder {
	return fn(params)
}

// UploadChunkHandler interface for that can handle valid upload chunk params
type UploadChunkHandler interface {
	Handle(UploadChunkParams) middleware.Responder
}

// NewUploadChunk creates a new http.Handler for the upload chunk operation
func NewUploadChunk(ctx *middleware.Context, handler UploadChunkHandler) *UploadChunk {
	return &UploadChunk{Context: ctx, Handler: handler}
}

/*
	UploadChunk swagger:route POST /files/upload uploadChunk

upload a chunk of the previously initialized file
*/
type UploadChunk struct {
	Context *middleware.Context
	Handler UploadChunkHandler
}

func (o *UploadChunk) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUploadChunkParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
