// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Zip processing
//
//	API for zip processing
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /
//	Version: 1.0.0
//
//	Consumes:
//	  - application/octet-stream
//	  - application/json
//
//	Produces:
//	  - application/octet-stream
//	  - application/json
//
// swagger:meta
package restapi
