// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetFilesParams creates a new GetFilesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetFilesParams() *GetFilesParams {
	return &GetFilesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetFilesParamsWithTimeout creates a new GetFilesParams object
// with the ability to set a timeout on a request.
func NewGetFilesParamsWithTimeout(timeout time.Duration) *GetFilesParams {
	return &GetFilesParams{
		timeout: timeout,
	}
}

// NewGetFilesParamsWithContext creates a new GetFilesParams object
// with the ability to set a context for a request.
func NewGetFilesParamsWithContext(ctx context.Context) *GetFilesParams {
	return &GetFilesParams{
		Context: ctx,
	}
}

// NewGetFilesParamsWithHTTPClient creates a new GetFilesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetFilesParamsWithHTTPClient(client *http.Client) *GetFilesParams {
	return &GetFilesParams{
		HTTPClient: client,
	}
}

/*
GetFilesParams contains all the parameters to send to the API endpoint

	for the get files operation.

	Typically these are written to a http.Request.
*/
type GetFilesParams struct {

	/* ID.

	   archive uid

	   Format: int64
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get files params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetFilesParams) WithDefaults() *GetFilesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get files params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetFilesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get files params
func (o *GetFilesParams) WithTimeout(timeout time.Duration) *GetFilesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get files params
func (o *GetFilesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get files params
func (o *GetFilesParams) WithContext(ctx context.Context) *GetFilesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get files params
func (o *GetFilesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get files params
func (o *GetFilesParams) WithHTTPClient(client *http.Client) *GetFilesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get files params
func (o *GetFilesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get files params
func (o *GetFilesParams) WithID(id int64) *GetFilesParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get files params
func (o *GetFilesParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetFilesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param id
	qrID := o.ID
	qID := swag.FormatInt64(qrID)
	if qID != "" {

		if err := r.SetQueryParam("id", qID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
