// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kaz-as/zip/models"
)

// InitUploadArchiveReader is a Reader for the InitUploadArchive structure.
type InitUploadArchiveReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *InitUploadArchiveReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewInitUploadArchiveOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewInitUploadArchiveDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewInitUploadArchiveOK creates a InitUploadArchiveOK with default headers values
func NewInitUploadArchiveOK() *InitUploadArchiveOK {
	return &InitUploadArchiveOK{}
}

/*
InitUploadArchiveOK describes a response with status code 200, with default header values.

new upload initialized
*/
type InitUploadArchiveOK struct {
	Payload *models.InitUploadSuccess
}

// IsSuccess returns true when this init upload archive o k response has a 2xx status code
func (o *InitUploadArchiveOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this init upload archive o k response has a 3xx status code
func (o *InitUploadArchiveOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this init upload archive o k response has a 4xx status code
func (o *InitUploadArchiveOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this init upload archive o k response has a 5xx status code
func (o *InitUploadArchiveOK) IsServerError() bool {
	return false
}

// IsCode returns true when this init upload archive o k response a status code equal to that given
func (o *InitUploadArchiveOK) IsCode(code int) bool {
	return code == 200
}

func (o *InitUploadArchiveOK) Error() string {
	return fmt.Sprintf("[POST /files][%d] initUploadArchiveOK  %+v", 200, o.Payload)
}

func (o *InitUploadArchiveOK) String() string {
	return fmt.Sprintf("[POST /files][%d] initUploadArchiveOK  %+v", 200, o.Payload)
}

func (o *InitUploadArchiveOK) GetPayload() *models.InitUploadSuccess {
	return o.Payload
}

func (o *InitUploadArchiveOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InitUploadSuccess)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewInitUploadArchiveDefault creates a InitUploadArchiveDefault with default headers values
func NewInitUploadArchiveDefault(code int) *InitUploadArchiveDefault {
	return &InitUploadArchiveDefault{
		_statusCode: code,
	}
}

/*
InitUploadArchiveDefault describes a response with status code -1, with default header values.

generic error response
*/
type InitUploadArchiveDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the init upload archive default response
func (o *InitUploadArchiveDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this init upload archive default response has a 2xx status code
func (o *InitUploadArchiveDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this init upload archive default response has a 3xx status code
func (o *InitUploadArchiveDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this init upload archive default response has a 4xx status code
func (o *InitUploadArchiveDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this init upload archive default response has a 5xx status code
func (o *InitUploadArchiveDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this init upload archive default response a status code equal to that given
func (o *InitUploadArchiveDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *InitUploadArchiveDefault) Error() string {
	return fmt.Sprintf("[POST /files][%d] initUploadArchive default  %+v", o._statusCode, o.Payload)
}

func (o *InitUploadArchiveDefault) String() string {
	return fmt.Sprintf("[POST /files][%d] initUploadArchive default  %+v", o._statusCode, o.Payload)
}

func (o *InitUploadArchiveDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *InitUploadArchiveDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
