// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// ArchiveName archive name
//
// swagger:model ArchiveName
type ArchiveName string

// Validate validates this archive name
func (m ArchiveName) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.Pattern("", "body", string(m), `^[a-zA-Z0-9._-][a-zA-Z0-9._ -]{,63}$`); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this archive name based on context it is used
func (m ArchiveName) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
