// Code generated by go-swagger; DO NOT EDIT.

package models

import "io"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// ChunkUploadingParam chunk uploading param
//
// swagger:model ChunkUploadingParam
type ChunkUploadingParam io.ReadCloser
