// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// ChunkNumber chunk's number or count
//
// swagger:model ChunkNumber
type ChunkNumber int32

// Validate validates this chunk number
func (m ChunkNumber) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this chunk number based on context it is used
func (m ChunkNumber) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
