// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// FilePath file path (without its name) in its source archive
//
// swagger:model FilePath
type FilePath []string

// Validate validates this file path
func (m FilePath) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this file path based on context it is used
func (m FilePath) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
