// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// FilePath file path (without its name) in its source archive
//
// swagger:model FilePath
type FilePath []string

// Validate validates this file path
func (m FilePath) Validate(formats strfmt.Registry) error {
	var res []error

	iFilePathSize := int64(len(m))

	if err := validate.MaxItems("", "body", iFilePathSize, 4); err != nil {
		return err
	}

	for i := 0; i < len(m); i++ {

		if err := validate.Pattern(strconv.Itoa(i), "body", m[i], `^[a-zA-Z0-9._-][a-zA-Z0-9._ -]{,31}$`); err != nil {
			return err
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this file path based on context it is used
func (m FilePath) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
