// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// FileName file name
//
// swagger:model FileName
type FileName string

// Validate validates this file name
func (m FileName) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.Pattern("", "body", string(m), `^[a-zA-Z0-9._-][a-zA-Z0-9._ -]{,63}$`); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this file name based on context it is used
func (m FileName) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
